// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlzkfgvbvjcjajcconzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsemtmZ3ZidmpjamFqY2Nvbnp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2MDc3NTIsImV4cCI6MjA1NDE4Mzc1Mn0.zf9d2PcDUds0cXgiFhfFYQ5CZnbSLlsA71yE57shbIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);